// @generated by protoc-gen-connect-web v0.3.3 with parameter "target=ts"
// @generated from file service.proto (syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { SendNotificationRequest } from "./service_pb.js";
import { Empty, MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service NotificationService
 */
export const NotificationService = {
  typeName: "NotificationService",
  methods: {
    /**
     * @generated from rpc NotificationService.SendNotification
     */
    sendNotification: {
      name: "SendNotification",
      I: SendNotificationRequest,
      O: Empty,
      kind: MethodKind.Unary,
    },
  }
} as const;

